minesweeper_ncurses: minesweeper_ncurses.c ../dadactyl/keymaps/default/minesweeper.c
	gcc -I../dadactyl/keymaps/default -g -o minesweeper_ncurses minesweeper_ncurses.c ../dadactyl/keymaps/default/minesweeper.c -lncurses

clean:
	rm -f minesweeper_ncurses log.txt
